version: '3.2'
services:
  backend:
    image: xarcher/crowd-back-server:lastest
    working_dir: /app/src
    expose:
      - 4000
    ports:
      - "0.0.0.0:4000:4000"
    environment:
      - GOPATH=/app
    command: go run main.go
    networks:
      chain:
  frontend:
    environment:
      - SERVER_PATH=wss://open-crowd-demo.site:4000
      - HTTP_PATH=https://open-crowd-demo.site:4000
    image: xarcher/crowd-front:latest
    depends_on:
      - backend
    ports:
      - "80:8080"
      - "443:8080"
    command: bash -c "npm run build && http-server dist -S -C pem/cert.pem -K pem/key.pem"
  client:
    image: xarcher/crowd-back-client:lastest
    working_dir: /app/src
    environment:
      - GOPATH=/app
    depends_on:
      - backend
    command: go run main.go -addr "open-crowd-demo.site:4000" -number 20
    networks:
      chain:
networks:
  chain:
#volumes:
#  chain_data: