version: '3.2'
services:
  backend:
    image: xarcher/crowd-back-server:lastest
    expose:
      - 4000
    ports:
      - "0.0.0.0:4000:4000"
    working_dir: /go-project/src/Percome19-Crowd-Demo/back-end
    volumes:
      - type: bind
        source: back-end
        target: /go-project/src/Percome19-Crowd-Demo/back-end
    environment:
      - GOPATH=/go-project
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
    command: go run main.go -chainPort "wss://kovan.infura.io/ws"
    networks:
      chain:
  frontend:
    working_dir: /app
    environment:
      - SERVER_PATH=wss://crowd.secdevgame.site:4000
      - HTTP_PATH=https://crowd.secdevgame.site:4000
    image: xarcher/crowd-front:latest
    depends_on:
      - backend
    volumes:
      - type: bind
        source: front-end
        target: /app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
    ports:
      - "80:8080"
      - "443:8080"
    command: bash -c "npm run build && http-server dist -S -C pem/cert.pem -K pem/key.pem"
  client:
    image: xarcher/crowd-back-client:lastest
    working_dir: /go-project/src/Percome19-Crowd-Demo/client
    volumes:
      - type: bind
        source: client
        target: /go-project/src/Percome19-Crowd-Demo/client
    environment:
      - GOPATH=/go-project
    depends_on:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
    command: go run main.go -addr "crowd.secdevgame.site:4000" -number 20
    networks:
      chain:
networks:
  chain:
volumes:
  backend: