version: '3.2'
services:
  backend:
    build: .
    image: xarcher/crowd-back-server:lastest
    working_dir: /go-project/src/Percome19-Crowd-Demo/back-end
    ports:
    - "4000:4000"
    environment:
    - GOPATH=/go-project
    command: go run main.go -chainPort "wss://kovan.infura.io/ws"
