version: '3.2'
services:
  backend:
    build: .
    image: xarcher/crowd-back-server:lastest
    working_dir: /app/src
    ports:
    - "4000:4000"
    environment:
    - GOPATH=/app
    command: go run main.go
